import {
  CompetitionConfig,
  CompetitionCode,
  CompetitionTemplateSummary,
  CycleSummary,
  PhaseDefinition,
} from "./types";

const olympicPipeline: PhaseDefinition[] = [
  { key: "teams", label: "Teams", route: "/teams", legacyPhase: 1 },
  { key: "roster", label: "Roster", route: "/roster", legacyPhase: 2 },
  { key: "mixed-groups", label: "Mixed Groups", route: "/mixed-groups", legacyPhase: 3 },
  { key: "rotation", label: "Rotation", route: "/rotation", legacyPhase: 4 },
  { key: "scoring", label: "Scores", route: "/scoring", legacyPhase: 5 },
  { key: "results", label: "Results", route: "/results", legacyPhase: 6 },
  { key: "finals", label: "Finals", route: "/finals", legacyPhase: 7, isTerminal: true },
];

const worldCupPipeline: PhaseDefinition[] = [
  { key: "entries", label: "Entries", route: "/entries" },
  { key: "rotation", label: "Rotation", route: "/rotation" },
  { key: "scoring", label: "Scores", route: "/scoring" },
  { key: "results", label: "Results", route: "/results" },
  { key: "finals", label: "Finals", route: "/finals", isTerminal: true },
];

export const FIG_PARIS_2024_CONFIGS: Record<CompetitionCode, CompetitionConfig> = {
  OLYMPICS_WAG_2024: {
    competitionCode: "OLYMPICS_WAG_2024",
    competitionKind: "OLYMPICS",
    cycleId: "fig-paris-2024",
    discipline: "WAG",
    year: 2024,
    label: "Paris 2024 Olympics - WAG",
    shortLabel: "Olympics WAG",
    locationLabel: "Paris 2024",
    phasePipeline: olympicPipeline,
    resultStrategies: [
      { channel: "TEAM", mode: "qualification_only" },
      { channel: "TEAM_APP", mode: "qualification_only" },
      { channel: "AA", mode: "qualification_only" },
      { channel: "APPARATUS", mode: "qualification_only" },
      { channel: "MEDAL_SUMMARY", mode: "finals_based" },
    ],
    quotaStrategy: "none",
    entryConstraints: {
      selectedCountryCount: 12,
      rosterFormats: [3, 5],
      mixedGroupCount: 8,
      mixedGymnastTotal: 36,
      subdivisionCount: 5,
      entitiesPerSubdivision: 4,
      qualificationRotationCount: 4,
    },
    uiCapabilities: {
      supportsQuickSetup: true,
      supportsCountrySelection: true,
      supportsRosterBuilder: true,
      supportsEntryBuilder: false,
      supportsMixedGroups: true,
      supportsTeamResults: true,
      supportsTeamApparatusResults: true,
      supportsAllAroundResults: true,
      supportsFinalsHub: true,
      supportsTeamFinal: true,
      supportsAllAroundFinal: true,
      supportsMedalSummary: true,
    },
    finalsConfiguration: {
      hasTeamFinal: true,
      hasAAFinal: true,
      hasApparatusFinals: true,
      medalSummaryUnlockedBy: ["TEAM", "AA", "APPARATUS"],
    },
  },
  OLYMPICS_MAG_2024: {
    competitionCode: "OLYMPICS_MAG_2024",
    competitionKind: "OLYMPICS",
    cycleId: "fig-paris-2024",
    discipline: "MAG",
    year: 2024,
    label: "Paris 2024 Olympics - MAG",
    shortLabel: "Olympics MAG",
    locationLabel: "Paris 2024",
    phasePipeline: olympicPipeline,
    resultStrategies: [
      { channel: "TEAM", mode: "qualification_only" },
      { channel: "TEAM_APP", mode: "qualification_only" },
      { channel: "AA", mode: "qualification_only" },
      { channel: "APPARATUS", mode: "qualification_only" },
      { channel: "MEDAL_SUMMARY", mode: "finals_based" },
    ],
    quotaStrategy: "none",
    entryConstraints: {
      selectedCountryCount: 12,
      rosterFormats: [3, 5],
      mixedGroupCount: 6,
      mixedGymnastTotal: 36,
      subdivisionCount: 3,
      entitiesPerSubdivision: 6,
      qualificationRotationCount: 6,
    },
    uiCapabilities: {
      supportsQuickSetup: true,
      supportsCountrySelection: true,
      supportsRosterBuilder: true,
      supportsEntryBuilder: false,
      supportsMixedGroups: true,
      supportsTeamResults: true,
      supportsTeamApparatusResults: true,
      supportsAllAroundResults: true,
      supportsFinalsHub: true,
      supportsTeamFinal: true,
      supportsAllAroundFinal: true,
      supportsMedalSummary: true,
    },
    finalsConfiguration: {
      hasTeamFinal: true,
      hasAAFinal: true,
      hasApparatusFinals: true,
      medalSummaryUnlockedBy: ["TEAM", "AA", "APPARATUS"],
    },
  },
  WORLD_CUP_WAG_2024: {
    competitionCode: "WORLD_CUP_WAG_2024",
    competitionKind: "WORLD_CUP",
    cycleId: "fig-paris-2024",
    discipline: "WAG",
    year: 2024,
    label: "FIG World Cup Series - WAG",
    shortLabel: "World Cup WAG",
    locationLabel: "FIG World Cup",
    phasePipeline: worldCupPipeline,
    resultStrategies: [
      { channel: "APPARATUS", mode: "mixed" },
      { channel: "MEDAL_SUMMARY", mode: "finals_based" },
    ],
    quotaStrategy: "world_cup_series",
    entryConstraints: {
      maxGymnastsPerCountry: 4,
      maxGymnastsTotal: 70,
      maxPerApparatus: 2,
      subdivisionCount: 4,
      entitiesPerSubdivision: 5,
      qualificationRotationCount: 4,
    },
    uiCapabilities: {
      supportsQuickSetup: false,
      supportsCountrySelection: false,
      supportsRosterBuilder: false,
      supportsEntryBuilder: true,
      supportsMixedGroups: false,
      supportsTeamResults: false,
      supportsTeamApparatusResults: false,
      supportsAllAroundResults: false,
      supportsFinalsHub: true,
      supportsTeamFinal: false,
      supportsAllAroundFinal: false,
      supportsMedalSummary: true,
    },
    finalsConfiguration: {
      hasTeamFinal: false,
      hasAAFinal: false,
      hasApparatusFinals: true,
      medalSummaryUnlockedBy: ["APPARATUS"],
    },
  },
  WORLD_CUP_MAG_2024: {
    competitionCode: "WORLD_CUP_MAG_2024",
    competitionKind: "WORLD_CUP",
    cycleId: "fig-paris-2024",
    discipline: "MAG",
    year: 2024,
    label: "FIG World Cup Series - MAG",
    shortLabel: "World Cup MAG",
    locationLabel: "FIG World Cup",
    phasePipeline: worldCupPipeline,
    resultStrategies: [
      { channel: "APPARATUS", mode: "mixed" },
      { channel: "MEDAL_SUMMARY", mode: "finals_based" },
    ],
    quotaStrategy: "world_cup_series",
    entryConstraints: {
      maxGymnastsPerCountry: 4,
      maxGymnastsTotal: 70,
      maxPerApparatus: 2,
      subdivisionCount: 4,
      entitiesPerSubdivision: 5,
      qualificationRotationCount: 6,
    },
    uiCapabilities: {
      supportsQuickSetup: false,
      supportsCountrySelection: false,
      supportsRosterBuilder: false,
      supportsEntryBuilder: true,
      supportsMixedGroups: false,
      supportsTeamResults: false,
      supportsTeamApparatusResults: false,
      supportsAllAroundResults: false,
      supportsFinalsHub: true,
      supportsTeamFinal: false,
      supportsAllAroundFinal: false,
      supportsMedalSummary: true,
    },
    finalsConfiguration: {
      hasTeamFinal: false,
      hasAAFinal: false,
      hasApparatusFinals: true,
      medalSummaryUnlockedBy: ["APPARATUS"],
    },
  },
};

export const FIG_PARIS_2024_CYCLE: CycleSummary = {
  cycleId: "fig-paris-2024",
  label: "FIG Paris 2024 Olympic Cycle",
  description:
    "Static competition matrix for the Paris 2024 cycle. The current implementation ships Olympics and apparatus World Cups as playable templates.",
  years: [
    {
      year: 2024,
      items: Object.values(FIG_PARIS_2024_CONFIGS).map<CompetitionTemplateSummary>((config) => ({
        competitionCode: config.competitionCode,
        cycleId: config.cycleId,
        discipline: config.discipline,
        year: config.year,
        label: config.label,
        shortLabel: config.shortLabel,
        competitionKind: config.competitionKind,
      })),
    },
  ],
};
