import { Country } from "./types";

export const COUNTRIES: Country[] = [
  { id: 'USA', name: 'USA', flag: '🇺🇸' },
  { id: 'ROC', name: 'Russia (ROC)', flag: '🇷🇺' },
  { id: 'CHN', name: 'China', flag: '🇨🇳' },
  { id: 'GBR', name: 'Great Britain', flag: '🇬🇧' },
  { id: 'AUS', name: 'Australia', flag: '🇦🇺' },
  { id: 'CAN', name: 'Canada', flag: '🇨🇦' },
  { id: 'ITA', name: 'Italy', flag: '🇮🇹' },
  { id: 'FRA', name: 'France', flag: '🇫🇷' },
  { id: 'GER', name: 'Germany', flag: '🇩🇪' },
  { id: 'BRA', name: 'Brazil', flag: '🇧🇷' },
  { id: 'JPN', name: 'Japan', flag: '🇯🇵' },
  { id: 'NED', name: 'Netherlands', flag: '🇳🇱' },
  { id: 'BEL', name: 'Belgium', flag: '🇧🇪' },
  { id: 'SUI', name: 'Switzerland', flag: '🇨🇭' },
  { id: 'ROU', name: 'Romania', flag: '🇷🇴' },
  { id: 'HUN', name: 'Hungary', flag: '🇭🇺' },
  { id: 'UKR', name: 'Ukraine', flag: '🇺🇦' },
  { id: 'KOR', name: 'South Korea', flag: '🇰🇷' },
  { id: 'UZB', name: 'Uzbekistan', flag: '🇺🇿' },
  { id: 'AZE', name: 'Azerbaijan', flag: '🇦🇿' },
  { id: 'TUR', name: 'Turkey', flag: '🇹🇷' },
  { id: 'ESP', name: 'Spain', flag: '🇪🇸' },
  { id: 'FIN', name: 'Finland', flag: '🇫🇮' },
  { id: 'SWE', name: 'Sweden', flag: '🇸🇪' },
  { id: 'NOR', name: 'Norway', flag: '🇳🇴' },
  { id: 'DEN', name: 'Denmark', flag: '🇩🇰' },
  { id: 'POL', name: 'Poland', flag: '🇵🇱' },
  { id: 'CZE', name: 'Czech Republic', flag: '🇨🇿' },
  { id: 'SVK', name: 'Slovakia', flag: '🇸🇰' },
  { id: 'AUT', name: 'Austria', flag: '🇦🇹' },
  { id: 'NZL', name: 'New Zealand', flag: '🇳🇿' },
  { id: 'MEX', name: 'Mexico', flag: '🇲🇽' },
  { id: 'COL', name: 'Colombia', flag: '🇨🇴' },
  { id: 'ARG', name: 'Argentina', flag: '🇦🇷' },
  { id: 'CUB', name: 'Cuba', flag: '🇨🇺' },
  { id: 'VEN', name: 'Venezuela', flag: '🇻🇪' },
  { id: 'EGY', name: 'Egypt', flag: '🇪🇬' },
  { id: 'RSA', name: 'South Africa', flag: '🇿🇦' },
  { id: 'ISR', name: 'Israel', flag: '🇮🇱' },
  { id: 'IND', name: 'India', flag: '🇮🇳' },
  { id: 'KAZ', name: 'Kazakhstan', flag: '🇰🇿' },
  { id: 'TJK', name: 'Tajikistan', flag: '🇹🇯' },
  { id: 'BLR', name: 'Belarus', flag: '🇧🇾' },
  { id: 'GEO', name: 'Georgia', flag: '🇬🇪' },
  { id: 'ARM', name: 'Armenia', flag: '🇦🇲' },
  { id: 'LAT', name: 'Latvia', flag: '🇱🇻' },
  { id: 'EST', name: 'Estonia', flag: '🇪🇪' },
  { id: 'LTU', name: 'Lithuania', flag: '🇱🇹' },
  { id: 'SLO', name: 'Slovenia', flag: '🇸🇮' },
  { id: 'CRO', name: 'Croatia', flag: '🇭🇷' },
  { id: 'SRB', name: 'Serbia', flag: '🇷🇸' },
  { id: 'BUL', name: 'Bulgaria', flag: '🇧🇬' },
  { id: 'GRE', name: 'Greece', flag: '🇬🇷' },
  { id: 'POR', name: 'Portugal', flag: '🇵🇹' },
  { id: 'THA', name: 'Thailand', flag: '🇹🇭' },
  { id: 'INA', name: 'Indonesia', flag: '🇮🇩' },
  { id: 'PHI', name: 'Philippines', flag: '🇵🇭' },
  { id: 'MAS', name: 'Malaysia', flag: '🇲🇾' },
  { id: 'SGP', name: 'Singapore', flag: '🇸🇬' },
  { id: 'HKG', name: 'Hong Kong', flag: '🇭🇰' },
  { id: 'ALG', name: 'Algeria', flag: '🇩🇿' },
  { id: 'PRK', name: 'North Korea', flag: '🇰🇵' },
  { id: 'PAN', name: 'Panama', flag: '🇵🇦' },
  { id: 'HAI', name: 'Haiti', flag: '🇭🇹' },
  { id: 'TPE', name: 'Chinese Taipei', flag: '🇹🇼' }
];

export const getCountryById = (id: string): Country => {
  return COUNTRIES.find(c => c.id === id) || { id, name: id, flag: '🏳️' };
};
