import { Country } from "./types";

export const COUNTRIES: Country[] = [
  { id: 'ALG', name: 'Algeria', flag: '\uD83C\uDDE9\uD83C\uDDFF' },
  { id: 'ARG', name: 'Argentina', flag: '\uD83C\uDDE6\uD83C\uDDF7' },
  { id: 'ARM', name: 'Armenia', flag: '\uD83C\uDDE6\uD83C\uDDF2' },
  { id: 'AUS', name: 'Australia', flag: '\uD83C\uDDE6\uD83C\uDDFA' },
  { id: 'AUT', name: 'Austria', flag: '\uD83C\uDDE6\uD83C\uDDF9' },
  { id: 'AZE', name: 'Azerbaijan', flag: '\uD83C\uDDE6\uD83C\uDDFF' },
  { id: 'BLR', name: 'Belarus', flag: '\uD83C\uDDE7\uD83C\uDDFE' },
  { id: 'BEL', name: 'Belgium', flag: '\uD83C\uDDE7\uD83C\uDDEA' },
  { id: 'BRA', name: 'Brazil', flag: '\uD83C\uDDE7\uD83C\uDDF7' },
  { id: 'BUL', name: 'Bulgaria', flag: '\uD83C\uDDE7\uD83C\uDDEC' },
  { id: 'CAN', name: 'Canada', flag: '\uD83C\uDDE8\uD83C\uDDE6' },
  { id: 'CHN', name: 'China', flag: '\uD83C\uDDE8\uD83C\uDDF3' },
  { id: 'TPE', name: 'Chinese Taipei', flag: '\uD83C\uDDF9\uD83C\uDDFC' },
  { id: 'COL', name: 'Colombia', flag: '\uD83C\uDDE8\uD83C\uDDF4' },
  { id: 'CRO', name: 'Croatia', flag: '\uD83C\uDDED\uD83C\uDDF7' },
  { id: 'CUB', name: 'Cuba', flag: '\uD83C\uDDE8\uD83C\uDDFA' },
  { id: 'CZE', name: 'Czech Republic', flag: '\uD83C\uDDE8\uD83C\uDDFF' },
  { id: 'DEN', name: 'Denmark', flag: '\uD83C\uDDE9\uD83C\uDDF0' },
  { id: 'EGY', name: 'Egypt', flag: '\uD83C\uDDEA\uD83C\uDDEC' },
  { id: 'EST', name: 'Estonia', flag: '\uD83C\uDDEA\uD83C\uDDEA' },
  { id: 'FIN', name: 'Finland', flag: '\uD83C\uDDEB\uD83C\uDDEE' },
  { id: 'FRA', name: 'France', flag: '\uD83C\uDDEB\uD83C\uDDF7' },
  { id: 'GEO', name: 'Georgia', flag: '\uD83C\uDDEC\uD83C\uDDEA' },
  { id: 'GER', name: 'Germany', flag: '\uD83C\uDDE9\uD83C\uDDEA' },
  { id: 'GRE', name: 'Greece', flag: '\uD83C\uDDEC\uD83C\uDDF7' },
  { id: 'GBR', name: 'Great Britain', flag: '\uD83C\uDDEC\uD83C\uDDE7' },
  { id: 'HAI', name: 'Haiti', flag: '\uD83C\uDDED\uD83C\uDDF9' },
  { id: 'HKG', name: 'Hong Kong', flag: '\uD83C\uDDED\uD83C\uDDF0' },
  { id: 'HUN', name: 'Hungary', flag: '\uD83C\uDDED\uD83C\uDDFA' },
  { id: 'IND', name: 'India', flag: '\uD83C\uDDEE\uD83C\uDDF3' },
  { id: 'INA', name: 'Indonesia', flag: '\uD83C\uDDEE\uD83C\uDDE9' },
  { id: 'ISR', name: 'Israel', flag: '\uD83C\uDDEE\uD83C\uDDF1' },
  { id: 'ITA', name: 'Italy', flag: '\uD83C\uDDEE\uD83C\uDDF9' },
  { id: 'JPN', name: 'Japan', flag: '\uD83C\uDDEF\uD83C\uDDF5' },
  { id: 'KAZ', name: 'Kazakhstan', flag: '\uD83C\uDDF0\uD83C\uDDFF' },
  { id: 'LAT', name: 'Latvia', flag: '\uD83C\uDDF1\uD83C\uDDFB' },
  { id: 'LTU', name: 'Lithuania', flag: '\uD83C\uDDF1\uD83C\uDDF9' },
  { id: 'MAS', name: 'Malaysia', flag: '\uD83C\uDDF2\uD83C\uDDFE' },
  { id: 'MEX', name: 'Mexico', flag: '\uD83C\uDDF2\uD83C\uDDFD' },
  { id: 'NED', name: 'Netherlands', flag: '\uD83C\uDDF3\uD83C\uDDF1' },
  { id: 'NZL', name: 'New Zealand', flag: '\uD83C\uDDF3\uD83C\uDDFF' },
  { id: 'PRK', name: 'North Korea', flag: '\uD83C\uDDF0\uD83C\uDDF5' },
  { id: 'NOR', name: 'Norway', flag: '\uD83C\uDDF3\uD83C\uDDF4' },
  { id: 'PAN', name: 'Panama', flag: '\uD83C\uDDF5\uD83C\uDDE6' },
  { id: 'PHI', name: 'Philippines', flag: '\uD83C\uDDF5\uD83C\uDDED' },
  { id: 'POL', name: 'Poland', flag: '\uD83C\uDDF5\uD83C\uDDF1' },
  { id: 'POR', name: 'Portugal', flag: '\uD83C\uDDF5\uD83C\uDDF9' },
  { id: 'ROU', name: 'Romania', flag: '\uD83C\uDDF7\uD83C\uDDF4' },
  { id: 'ROC', name: 'Russia (ROC)', flag: '\uD83C\uDDF7\uD83C\uDDFA' },
  { id: 'SRB', name: 'Serbia', flag: '\uD83C\uDDF7\uD83C\uDDF8' },
  { id: 'SGP', name: 'Singapore', flag: '\uD83C\uDDF8\uD83C\uDDEC' },
  { id: 'SVK', name: 'Slovakia', flag: '\uD83C\uDDF8\uD83C\uDDF0' },
  { id: 'SLO', name: 'Slovenia', flag: '\uD83C\uDDF8\uD83C\uDDEE' },
  { id: 'RSA', name: 'South Africa', flag: '\uD83C\uDDFF\uD83C\uDDE6' },
  { id: 'KOR', name: 'South Korea', flag: '\uD83C\uDDF0\uD83C\uDDF7' },
  { id: 'ESP', name: 'Spain', flag: '\uD83C\uDDEA\uD83C\uDDF8' },
  { id: 'SWE', name: 'Sweden', flag: '\uD83C\uDDF8\uD83C\uDDEA' },
  { id: 'SUI', name: 'Switzerland', flag: '\uD83C\uDDE8\uD83C\uDDED' },
  { id: 'TJK', name: 'Tajikistan', flag: '\uD83C\uDDF9\uD83C\uDDEF' },
  { id: 'THA', name: 'Thailand', flag: '\uD83C\uDDF9\uD83C\uDDED' },
  { id: 'TUR', name: 'Turkey', flag: '\uD83C\uDDF9\uD83C\uDDF7' },
  { id: 'UKR', name: 'Ukraine', flag: '\uD83C\uDDFA\uD83C\uDDE6' },
  { id: 'USA', name: 'USA', flag: '\uD83C\uDDFA\uD83C\uDDF8' },
  { id: 'UZB', name: 'Uzbekistan', flag: '\uD83C\uDDFA\uD83C\uDDFF' },
  { id: 'VEN', name: 'Venezuela', flag: '\uD83C\uDDFB\uD83C\uDDEA' }
];

export const getCountryById = (id: string): Country => {
  return COUNTRIES.find(c => c.id === id) || { id, name: id, flag: '\uD83C\uDFF3\uFE0F' };
};
